### PR TITLE
Failed to update the K8S cluster certificate

### LINKED ISSUE #114: Failed to update the K8S cluster certificate
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
Kubernetes: v1.18.20
Kubeclipper: master

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.9 / 1 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Install v1.18.20 k8s.
2. View kc-server logs, `journalctl -u kc-server -f`
3. Kc-server has panic error, it will cause kc-server to restart

**Expected behavior**

### PR DESCRIPTION
**Pull request by Xvv-v**
Signed-off-by: Xvv-v <xu.jingwen@99cloud.net>

### What type of PR is this?
/kind bug

### Which issue(s) this PR fixes:

Fixes #114 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheme/core/v1/k8s/kubeadm_step.go [hunk 1]
```diff
@@ -48,6 +48,7 @@ const (
 	container       = "container"
 	kubectl         = "kubectl"
 	kubectlTerminal = "kubectlTerminal"
+	K8sVersion      = "1.20"
```
Comment (x893675) [inline pkg/scheme/core/v1/k8s/kubeadm_step.go:51]: variable name needs to be more clear
